version: "3"
services:
  backend-server:
    image: delowerhasandh/spohire-backend
    container_name: backend-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
