name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker-compose build
          docker-compose push

      - name: SSH into server and run command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.PASSWORD }}
         script: whoami
        # script: |
        #   echo "Logged in to the server"
        #   # Add your commands here

      # - name: Deploy to EC2 with SSH
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.AWS_HOST }}
      #     username: ${{ secrets.AWS_USERNAME }}
      #     key: ${{ secrets.AWS_SSH_KEY }}
      #     script: |
      #       cd /home/ubuntu/app
      #       docker-compose down
      #       docker system prune -af
      #       docker-compose pull
      #       docker-compose up -d
